package martinserranojava03;

import javax.swing.JButton;
import java.util.Calendar;
import java.util.GregorianCalendar;


/**
 *
 * @author Rafae
 */
public class NewJFrame extends javax.swing.JFrame {

    //Creamos los atributos necesarios//
    
    static Lista<Cuenta> Cuentas = new Lista<>(); //creamos nuestra lista con la cuent//
    static Cuenta actual; //creamos la cuenta actual//
    
    //banderas//
    static boolean EnCreacion = false;     //Si esta añadiendo una nueva cuenta o no

    //Variables//
    static int numCuen = 1; //para guardar el numero de cuenta//

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        super("Cuentas Bancarias"); //el nombre de nuestro panel//
        initComponents(); //iniciamos los componentes//
        actual= (Cuenta) Cuentas.getInicio().getDato(); //asignamos a actual la cuenta//
        texto(); //usamos la funcion texto//
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        numeroCuenta = new javax.swing.JTextField();
        propietario = new javax.swing.JTextField();
        fechaApertura = new javax.swing.JTextField();
        sueldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Atras.setText("Anterior");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        Crear.setText("Crear");
        Crear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        numeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroCuentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero de cuenta:");

        jLabel2.setText("Propietario");

        jLabel3.setText("Fecha Apertura");

        jLabel4.setText("Sueldo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fechaApertura, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(numeroCuenta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(propietario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sueldo))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Cuentas bancarias");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Crear)
                    .addComponent(Atras)
                    .addComponent(Siguiente))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        //Boton atras//
    
    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:
        if (!EnCreacion) { //preguntamos por la bandera//
            if (Cuentas.getActual().getAnterior() != null) { //luego por actual y anterior//

                Cuentas.setActual(Cuentas.getActual().getAnterior()); //asignamos la cuenta a la actual//
                actual = (Cuenta) Cuentas.getActual().getDato(); //cojemos los datos//

                //Recoger texto//
                numeroCuenta.setText("" + actual.getNumCuen());
                propietario.setText("" + actual.getPropi());
                fechaApertura.setText("" + actual.getFechap());
                sueldo.setText("" + actual.getSueld());

                //habilitar o deshabilitar boton//
                if(Cuentas.getActual().getSiguiente()!=null)
                    Siguiente.setEnabled(true); //si no es nulo lo activamos
                if(Cuentas.getActual().getAnterior()==null)
                    Atras.setEnabled(false); //si lo deshabilitamos el de atras//
            }
        } else {
            terminarCrear(Siguiente, Atras, Crear); //si no terminamos lafuncion//
        }
    }//GEN-LAST:event_AtrasActionPerformed

        //Boton siguiente//
    
    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
        if (!EnCreacion) { //preguntamos por la bandera
            
            //si la bandera no es nula//
            if (Cuentas.getActual().getSiguiente() != null) {

                Cuentas.setActual(Cuentas.getActual().getSiguiente()); //configuramos cuenta//
                actual = (Cuenta) Cuentas.getActual().getDato(); //Cogemos los datos//

                //Recoger texto//
                
                numeroCuenta.setText("" + actual.getNumCuen()); //numero de cuenta//
                propietario.setText("" + actual.getPropi()); //nombre propietario//
                fechaApertura.setText("" + actual.getFechap()); //fecha apertura//
                sueldo.setText("" + actual.getSueld()); //configuramos el texto mostrado//

                //habilitar o desabilitar boton//
                
                if(Cuentas.getActual().getSiguiente()==null)
                    Siguiente.setEnabled(false); //configuramos la visibilidad de siguiente//
                if(Cuentas.getActual().getAnterior()!=null)
                    Atras.setEnabled(true); //configuramos la visibilidad de atras//
            }
        } else { //si no es nulo//
            
            int numero = Integer.parseInt(numeroCuenta.getText()); //cojemos el numero introducido//
            int saldo = Integer.parseInt(sueldo.getText()); //el saldo introducido//
            Cuentas.insertarNodo(numero, saldo, propietario.getText()); //insertamos el nodo//
            
            //luego usaremos de nuevo la funcion para terminar de crear//
             
            terminarCrear(Siguiente, Atras, Crear);
        }
    }//GEN-LAST:event_SiguienteActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
      
        //Habilitamos los campos//
        
        sueldo.setEditable(true); //ponemos en true el sueldo//
        propietario.setEditable(true); //igual con el propietario//
        
        //Creamos una nueva fecha//
        
        GregorianCalendar fecha = new GregorianCalendar();
        
        //Ahora vaciamos los campos//
        
        numeroCuenta.setText(""+ numCuen); //numero de cuenta automatico//
        propietario.setText(""); //propietario//
        sueldo.setText(""); //sueldo//
     
        //Creamos la fecha de apertura//
            
        fechaApertura.setText(""+fecha.get(Calendar.DAY_OF_MONTH) + "/" //para el dia//
                + (fecha.get(Calendar.MONTH) + 1) + "/" //para el mes//
                + fecha.get(Calendar.YEAR)); //para el año//
        
        //Ahora cambiamos el texto de los botones//
        
        Atras.setText("Cancelar"); //atras sera cancelar//
        Siguiente.setText("Aceptar"); //siguiente sera aceptar//
        
        //Configuramos la visibilidad de los botones//
        
        Crear.setEnabled(false); //crear lo ponemos en falso//
        Siguiente.setEnabled(true); //siguiente lo mostramos para que sea aceptar//
        Atras.setEnabled(true); //lo mismo con atras,sera cancelar//
        
        //bajamos la bandera para indicar que hemos terminado de crear//
        
        EnCreacion = true;
    }//GEN-LAST:event_CrearActionPerformed

    private void terminarCrear(JButton Siguiente, JButton Atras, JButton Crear) {
        
        //configuramos el texto de los botones//
        
        Atras.setText("Atrás"); //boton atras//
        Siguiente.setText("Siguiente"); //boton siguiente//
        
        //Ponemos activo el boton crear y falso el de siguiente//
        
        Crear.setEnabled(true);  //boton crear en verdadero//
        Siguiente.setEnabled(false); //boton siguiente en falso//
        
        //Configuramos que el actual sea el final//
        
        Cuentas.setActual(Cuentas.getFin()); //guardamos en actual la cuenta final//
        actual = (Cuenta) Cuentas.getActual().getDato(); //casteamos en cuentas//

        //configuramos que no se pueda escribir en el camp//
        
        propietario.setEditable(false); //propietario//
        fechaApertura.setEditable(false); //fecha de apertura//
        numeroCuenta.setEditable(false); //numero de cuenta//
        sueldo.setEditable(false); //sueldo//


        EnCreacion = false; //Ponemos la bandera en falso//

        //Configuramos los campos de texto para que nos saque los datos//
        
        propietario.setText(""+actual.getPropi()); //propietario//
        fechaApertura.setText(""+actual.getFechap()); //fecha de apertura//
        numeroCuenta.setText(""+actual.getNumCuen()); //numero de cuenta//
        sueldo.setText(""+actual.getSueld()); //sueldo//

    }
    
    private void texto(){
        
        //Guardamos el texto recogido en el actual//
        
        propietario.setText(""+actual.getPropi()); //propietario//
        fechaApertura.setText(""+actual.getFechap()); //fecha apertura//
        numeroCuenta.setText(""+actual.getNumCuen()); //numero cuenta//
        sueldo.setText(""+actual.getSueld()); //sueldo//

        //Configuramos los botones/
        Atras.setEnabled(false); //ponemos en falso la bandera//
    }
    
    private void numeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        numCuen=Cuentas.introDat(numCuen); //cramos las cuentas iniciales//
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Siguiente;
    private javax.swing.JTextField fechaApertura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField numeroCuenta;
    private javax.swing.JTextField propietario;
    private javax.swing.JTextField sueldo;
    // End of variables declaration//GEN-END:variables
}
